name: report
on:
  workflow_run:
    workflows: [build]
    types: [completed]
    
permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
      - uses: 5monkeys/cobertura-action@master
        with:
          path: junit-reports/TEST-cov.xml
          show_missing: true
          minimum_coverage: 75
