name: report
on:
  workflow_run:
    workflows: [build]
    types: [completed]
permissions: write-all
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        with:
          name: junit-test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
          path: 'junit-reports'
        uses: dawidd6/action-download-artifact@v2
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
      - uses: 5monkeys/cobertura-action@master
        with:
          path: junit-reports/TEST-cov.xml
          show_missing: true
          minimum_coverage: 75
